apiVersion: v1alpha
kind: saucectl

sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    build: "build-${GITHUB_RUN_NUMBER}"

suites:
  - name: web-desktop
    framework: playwright

    run:
      - pnpm install --frozen-lockfile
      - npx cucumber-js --config cucumber.config.mjs

    env:
      PLATFORM: web
      DRIVER: playwright
      VIEWPORT: desktop
      BASE_URL: ${BASE_URL}
      HEADLESS: "true"
      LOG_LEVEL: info

  - name: web-responsive
    framework: playwright

    run:
      - pnpm install --frozen-lockfile
      - npx cucumber-js --config cucumber.config.mjs

    env:
      PLATFORM: web
      DRIVER: playwright
      VIEWPORT: responsive
      BASE_URL: ${BASE_URL}
      HEADLESS: "true"
      LOG_LEVEL: info
