apiVersion: saucectl.io/v1alpha
kind: saucectl

metadata:
  name: proxy-pattern-web

suites:
  # ============================
  # WEB – DESKTOP
  # ============================
  - name: web-desktop
    framework: playwright

    platformName: Windows 11
    browserName: chromium

    playwright:
      version: 1.42.0

    env:
      PLATFORM: web
      DRIVER: playwright
      VIEWPORT: desktop
      BASE_URL: ${BASE_URL}

    command: >
      pnpm test

  # ============================
  # WEB – RESPONSIVE
  # ============================
  - name: web-responsive
    framework: playwright

    platformName: Windows 11
    browserName: chromium

    playwright:
      version: 1.42.0

    env:
      PLATFORM: web
      DRIVER: playwright
      VIEWPORT: responsive
      BASE_URL: ${BASE_URL}

    command: >
      pnpm test